version: "2"

services:
  mysql:
    container_name: mysql
    image: idhar01/mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d/"
      - "./db/conf/my.cnf:/etc/my.cnf"
    networks:
      - xuexixitong
networks:
  xuexixitong:
    external: true
      